name = "project-pci-proxy"
main = "pci-proxy.js"
compatibility_date = "2024-11-01"

[vars]
ALLOWED_ORIGIN = "https://fibpmo.com,https://www.fibpmo.com,https://rudawathegw-design.github.io"
JIRA_BASE_URL = "https://fibtask.atlassian.net"
JIRA_PROJECT = "FIBXPI"
